// Combat — battle resolution constants (spec/combat.md).
// All numbers live in balance.ts — THE tuning file.

export {
  ACTION_TURNS,
  STAMINA,
  UNIT_STATS,
  TIER_POWER,
  ENGINE_FIRE,
  BUILDING_DAMAGE_PER_TREB,
  BUILDING_INTEGRITY_FLOOR,
  WALL_BOMBARD_PIVOT,
  ESCALADE_COVERAGE,
  MAX_ROUNDS,
  K_LETHALITY,
  BREAK_THRESHOLD,
  LUCK_SWING,
  WALL_BONUS_CURVE,
  XP,
  LOOT,
  REVENGE_WINDOW_HOURS,
  SIEGE_GEAR_LOSS_ON_DEFEAT,
  WALL_REPAIR_COST_FACTOR,
  SCATTERING,
} from "./balance";
